# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JKRepairApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JKRepairApp
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', subspecs: [
    'ART',
    'BatchedBridge',
    'DevSupport',
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
  ], path: '../node_modules/react-native'
  pod 'Firebase/Messaging'

  inherit! :search_paths

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end
